Add run_tests script that aborts on first failure.

diff --git a/run_tests b/run_tests
--- a/run_tests
+++ b/run_tests
@@ -1,3 +1,17 @@
 #!/bin/bash
 
-find Bin/Test -executable -type f -exec {} \;
+#find Bin/Test -executable -type f -exec {} \;
+tests=`find Bin/Test -executable -type f`
+
+
+for test in $tests
+do
+	echo "Running Test " $test
+	$test
+	if [[ $? -ne 0 ]]; then
+		echo
+		echo "Aborting remaining tests."
+		exit 1
+	fi
+done
+
